<?php

namespace App\Services;

use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Exception;
use Illuminate\Support\Facades\Log;

class UserService
{
    public function getUsers($perPage = 15, $search = null, $viewTrash = 'false')
    {
        try {
            $query = User::with('roles');

            if ($viewTrash === 'true') {
                $query->onlyTrashed();
            }

            if ($search) {
                $query->where(function ($q) use ($search) {
                    $q->where('name', 'like', "%{$search}%")
                      ->orWhere('email', 'like', "%{$search}%")
                      ->orWhere('mobile', 'like', "%{$search}%")
                      ->orWhere('referral_code', 'like', "%{$search}%");
                });
            }

            return $query->latest()->paginate($perPage);

        } catch (Exception $e) {
            Log::error("Error fetching users: " . $e->getMessage());
            throw new Exception("Unable to load users list at the moment.");
        }
    }

    public function createUser($data)
    {
        return DB::transaction(function () use ($data) {
            try {
                $userData = [
                    'name' => $data['name'],
                    'email' => $data['email'],
                    'mobile' => $data['mobile'] ?? null,
                    'gender' => $data['gender'] ?? null,
                    'dob' => $data['dob'] ?? null,
                    'state_id' => $data['state_id'] ?? null,
                    'city' => $data['city'] ?? null,
                    'password' => Hash::make($data['password']),
                    'kyc_status' => $data['kyc_status'] ?? 'not_submitted',
                    'is_active' => 1,
                ];

                // Manual Referral Code or Auto-generated by Model
                if (!empty($data['referral_code'])) {
                    $userData['referral_code'] = $data['referral_code'];
                }

                $user = User::create($userData);

                if (!empty($data['role'])) {
                    $user->assignRole($data['role']);
                }

                return $user;

            } catch (Exception $e) {
                Log::error("Error creating user: " . $e->getMessage());
                throw new Exception("Failed to create user. Please check the details and try again.");
            }
        });
    }

    public function updateUser($id, $data)
    {
        try {
            $user = User::findOrFail($id);

            $updateData = [
                'name' => $data['name'],
                'email' => $data['email'],
                'mobile' => $data['mobile'],
                'gender' => $data['gender'],
                'dob' => $data['dob'],
                'state_id' => $data['state_id'],
                'city' => $data['city'],
                'kyc_status' => $data['kyc_status'],
            ];

            if (!empty($data['password'])) {
                $updateData['password'] = Hash::make($data['password']);
            }

            if (!empty($data['referral_code'])) {
                $updateData['referral_code'] = $data['referral_code'];
            }

            $user->update($updateData);

            if (!empty($data['role'])) {
                $user->syncRoles([$data['role']]);
            }

            return $user;

        } catch (Exception $e) {
            Log::error("Error updating user ID $id: " . $e->getMessage());
            throw new Exception("Could not update user details.");
        }
    }

    public function toggleBan($id)
    {
        try {
            $user = User::findOrFail($id);
            $user->is_banned = !$user->is_banned;
            $user->banned_at = $user->is_banned ? now() : null;
            $user->save();
            return $user;
        } catch (Exception $e) {
            throw new Exception("Failed to change ban status.");
        }
    }

    public function deleteUser($id)
    {
        try {
            $user = User::findOrFail($id);
            $user->delete();
            return true;
        } catch (Exception $e) {
            throw new Exception("Failed to move user to trash.");
        }
    }

    public function restoreUser($id)
    {
        try {
            $user = User::withTrashed()->findOrFail($id);
            $user->restore();
            return true;
        } catch (Exception $e) {
            throw new Exception("Failed to restore user.");
        }
    }

    public function forceDeleteUser($id)
    {
        try {
            $user = User::withTrashed()->findOrFail($id);
            $user->forceDelete();
            return true;
        } catch (Exception $e) {
            throw new Exception("Failed to permanently delete user.");
        }
    }

    public function getUserDetails($id)
    {
        try {
            $user = User::with(['roles', 'referrer'])->find($id);
            if (!$user) {
                $user = User::withTrashed()->with(['roles', 'referrer'])->find($id);
            }
            if(!$user) throw new Exception("User not found.");
            return $user;
        } catch (Exception $e) {
            throw new Exception("Unable to fetch user profile.");
        }
    }
}
